# Generated by Django 5.1.6 on 2025-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='syllabus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
