# Generated by Django 5.2.3 on 2025-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_syllabus_uploadedfile_extraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='syllabus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
