# Generated by Django 5.2.3 on 2025-07-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_draft_cleanup_index'),
        ('projects', '0004_project_syllabus'),
    ]

    operations = [
    ]
