# Generated by Django 5.2.3 on 2025-07-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20250727_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProject',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='school_project_data', serialize=False, to='projects.project')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SelfStudyProject',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='self_study_project_data', serialize=False, to='projects.project')),
                ('goal_description', models.TextField()),
                ('study_frequency', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='project',
            name='school_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_project', to='projects.schoolproject'),
        ),
        migrations.AddField(
            model_name='project',
            name='self_study_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_project', to='projects.selfstudyproject'),
        ),
    ]
