# Generated by Django 5.2.3 on 2025-07-27 19:47

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_schoolproject_selfstudyproject_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'key'], name='projects_pr_project_d41c9f_idx'), django.contrib.postgres.indexes.GinIndex(fields=['value'], name='projectmeta_value_gin')],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
