# Generated by Django 5.2.3 on 2025-07-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_alter_flashcard_options_flashcard_difficulty_rating_and_more'),
        ('projects', '0007_add_project_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary flashcard set for this project')),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='generation.flashcardset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='projects.project')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('project', 'flashcard_set')},
            },
        ),
    ]
