name: maProject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django
  - pytest
  - pytest-django
  - libarchive  # This may help satisfy the libarchive dependency for libmamba if needed
  # Add any other dependencies your project requires
