# Default Configuration for Generation App
# This file provides default configuration values for all services

version: "1.3.0"
environment: "development"
debug_mode: false
log_level: "INFO"
cache_enabled: true

# Spaced Repetition Configuration
spaced_repetition:
  default_algorithm: "sm2"
  available_algorithms: ["sm2", "leitner", "super_memo_2"]
  
  # SM2 Algorithm parameters
  sm2_initial_ease_factor: 2.5
  sm2_minimum_ease_factor: 1.3
  sm2_ease_factor_bonus: 0.1
  sm2_ease_factor_penalty: 0.15
  
  # Leitner Algorithm parameters
  leitner_box_count: 5
  leitner_promotion_threshold: 2
  leitner_demotion_threshold: 1
  leitner_interval_multiplier: 2.0
  
  # General parameters
  max_interval_days: 365
  min_interval_days: 1
  grace_period_hours: 12
  review_quality_threshold: 0.6
  
  # Performance tuning
  batch_size: 100
  cache_ttl_seconds: 300
  max_concurrent_reviews: 10

# Interleaving Configuration
interleaving:
  # Session composition weights
  default_weights:
    due: 0.6
    interleave: 0.25
    new: 0.15
  
  # Session size configuration
  min_session_size: 5
  max_session_size: 50
  default_session_size: 15
  
  # Difficulty-based adjustments
  difficulty_multipliers:
    beginner: 0.8
    intermediate: 1.0
    advanced: 1.2
    expert: 1.5
  
  # Topic constraints
  max_same_topic_streak: 3
  min_topic_variety: 2
  require_contrast_pairs: true
  topic_balance_threshold: 0.3
  
  # Learning principle constraints
  max_same_principle_streak: 2
  principle_contrast_weight: 0.4
  adaptive_difficulty: true
  
  # Performance tuning
  constraint_solver_timeout: 30
  relaxation_iterations: 5
  cache_session_results: true

# Diagnostic Configuration
diagnostic:
  # Session timing
  default_time_limit_minutes: 30
  grace_period_minutes: 5
  auto_submit_delay_seconds: 300
  
  # Question configuration
  min_questions_per_session: 3
  max_questions_per_session: 20
  default_questions_per_session: 10
  
  # Question selection
  question_types: ["MCQ", "SHORT_ANSWER", "TRUE_FALSE"]
  bloom_levels: ["Remember", "Understand", "Apply", "Analyze"]
  difficulty_distribution:
    EASY: 0.3
    MEDIUM: 0.5
    HARD: 0.2
  
  # Feedback and scoring
  immediate_feedback: false
  show_correct_answers: true
  partial_credit: true
  adaptive_scoring: true
  
  # Performance tracking
  track_response_time: true
  track_hint_usage: true
  track_attempts: true
  analytics_enabled: true

# AI Provider Configuration
ai_provider:
  primary_provider: "gemini"
  fallback_providers: ["openai", "mock"]
  
  # API configuration
  api_keys: {}
  api_endpoints: {}
  request_timeout_seconds: 30
  
  # Rate limiting
  requests_per_minute: 60
  requests_per_hour: 1000
  burst_limit: 10
  
  # Model configuration
  default_models:
    gemini: "gemini-pro"
    openai: "gpt-4"
    anthropic: "claude-3-sonnet"
  
  # Fallback and retry
  max_retries: 3
  retry_delay_seconds: 1
  exponential_backoff: true
  circuit_breaker_enabled: true
  
  # Performance tuning
  connection_pool_size: 10
  keep_alive_timeout: 60
  cache_responses: true
  cache_ttl_seconds: 3600

# Feature Flags Configuration
feature_flags:
  # Core features
  spaced_repetition_enabled: true
  interleaving_enabled: true
  diagnostic_assessments_enabled: true
  ai_generation_enabled: true
  
  # Experimental features
  adaptive_learning_enabled: false
  social_learning_enabled: false
  gamification_enabled: false
  analytics_dashboard_enabled: true
  
  # Rollout percentages (0.0 to 1.0)
  feature_rollouts:
    adaptive_learning: 0.1
    social_learning: 0.05
    gamification: 0.2
    advanced_analytics: 0.3
  
  # User targeting
  beta_users: []
  admin_users: []
  feature_groups: {}
  
  # Environment-specific flags
  development_features: false
  staging_features: false
  production_features: true

# Enhanced Validation Configuration
validation:
  strict_mode: false
  auto_fix: true
  custom_rules: []
  cross_field_validation: true
  performance_checks: true
  security_checks: true

# Performance Monitoring Configuration
monitoring:
  enabled: true
  metrics_collection: true
  performance_tracking: true
  alert_thresholds:
    cache_hit_rate: 0.8
    response_time_ms: 1000
    error_rate: 0.05

# Cache Configuration
cache:
  default_ttl: 300
  max_memory_items: 100
  auto_optimize: true
  optimization_threshold: 0.1

# Security Configuration
security:
  api_key_rotation_days: 90
  rate_limit_strict: false
  audit_logging: true
  sensitive_field_masking: true
