# Generated by Django 5.1.6 on 2025-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
