# Generated by Django 5.2.4 on 2025-07-14 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_generatedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='algorithm',
            field=models.CharField(choices=[('leitner', 'Leitner System'), ('sm2', 'SM-2 Algorithm')], default='sm2', help_text='The spaced repetition algorithm to use for this card', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='correct_reviews',
            field=models.IntegerField(default=0, help_text='Number of correct reviews'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='SM-2 ease factor (influences interval growth rate)'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.FloatField(default=1.0, help_text='Current interval in days until next review'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, help_text='When this card was last reviewed', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='learning_state',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', help_text='Current learning state of the card', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='leitner_box',
            field=models.IntegerField(default=1, help_text='Current Leitner box (1-5, higher = longer intervals)'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='memory_strength',
            field=models.FloatField(default=1.0, help_text='Estimated memory strength (higher = more memorable)'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this card is due for review'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.IntegerField(default=0, help_text='Number of times this card has been successfully reviewed'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total number of times this card has been reviewed'),
        ),
    ]
