# Generated by Django 5.2.3 on 2025-07-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_spaced_repetition_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['next_review', 'updated_at']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='algorithm',
            field=models.CharField(choices=[('sm2', 'SM-2'), ('leitner', 'Leitner')], default='sm2', max_length=20),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='correct_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='learning_state',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='leitner_box',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='memory_strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set', 'next_review'], name='generation__flashca_30db5b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['learning_state', 'next_review'], name='generation__learnin_1c72b1_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['algorithm', 'next_review'], name='generation__algorit_694eb1_idx'),
        ),
    ]
