# Generated by Django 5.2.3 on 2025-08-14 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_simplified_flashcard_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardProfile',
            fields=[
                ('flashcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='generation.flashcard')),
                ('difficulty_est', models.FloatField(default=1.0)),
                ('surface_features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterleavingSessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10)),
                ('session_size', models.PositiveIntegerField(default=10)),
                ('w_due', models.FloatField(default=0.6)),
                ('w_interleave', models.FloatField(default=0.25)),
                ('w_new', models.FloatField(default=0.15)),
                ('max_same_topic_streak', models.PositiveIntegerField(default=2)),
                ('require_contrast_pair', models.BooleanField(default=True)),
                ('auto_adapt', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='flashcard',
            name='generation__algorit_694eb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='flashcard',
            name='generation__flashca_next_re_789012_idx',
        ),
        migrations.RenameIndex(
            model_name='flashcard',
            new_name='generation__next_re_e3734f_idx',
            old_name='generation__next_re_flashca_123456_idx',
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='content_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(default='flashcard', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interleavingsessionconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='principle',
            name='contrasts_with',
            field=models.ManyToManyField(blank=True, to='generation.principle'),
        ),
        migrations.AddField(
            model_name='flashcardprofile',
            name='principle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.principle'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.topic'),
        ),
        migrations.AddField(
            model_name='principle',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='generation.topic'),
        ),
        migrations.AddField(
            model_name='flashcardprofile',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.topic'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='generation__name_1ff580_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardprofile',
            index=models.Index(fields=['topic'], name='generation__topic_i_f76579_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardprofile',
            index=models.Index(fields=['principle'], name='generation__princip_e1a2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardprofile',
            index=models.Index(fields=['difficulty_est'], name='generation__difficu_ed25ac_idx'),
        ),
    ]
