# Generated by Django 5.2.3 on 2025-08-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0008_diagnosticquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='leitner_box',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
