# Generated by Django 5.2.3 on 2025-08-17 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0009_flashcard_leitner_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
