# Generated by Django 5.2.3 on 2025-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0010_change_next_review_to_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='bloom_level',
            field=models.CharField(choices=[('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='apply', max_length=15),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='card_type',
            field=models.CharField(choices=[('definition', 'Definition'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis'), ('evaluation', 'Evaluation'), ('problem_solving', 'Problem Solving'), ('comparison', 'Comparison'), ('critique', 'Critique'), ('cloze', 'Cloze'), ('scenario', 'Scenario')], default='definition', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='common_misconceptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='concept_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='learning_objective',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='related_concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
