# Generated by Django 5.2.4 on 2025-08-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_create_assessment_models'),
        ('generation', '0011_add_enhanced_flashcard_fields'),
    ]

    operations = [
    ]
