# Generated by Django 5.2.4 on 2025-09-01 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0013_delete_flashcard_delete_flashcardset_and_more'),
        ('pdf_service', '0006_document_error_message_alter_document_document_type'),
        ('projects', '0009_alter_projectflashcardset_flashcard_set_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentSet',
        ),
        migrations.AlterField(
            model_name='FlashcardProfile',
            name='flashcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='generation.flashcard'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='pdf_service.document'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='Flashcard',
            name='flashcard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='generation.flashcardset'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='generation.flashcardset'),
        ),
        migrations.DeleteModel(
            name='AssessmentItem',
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set', 'next_review'], name='generation__flashca_30db5b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['learning_state', 'next_review'], name='generation__learnin_1c72b1_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['next_review', 'flashcard_set'], name='generation__next_re_e3734f_idx'),
        ),
    ]
