# Generated by Django 5.2.6 on 2025-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0014_delete_assessmentset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsession',
            name='style_config_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='test_style',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
