# Generated by Django 5.1.6 on 2025-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_service', '0002_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
