# Generated by Django 5.1.6 on 2025-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_service', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_type',
            field=models.CharField(choices=[('course_files', 'Course Files'), ('test_files', 'Test Files'), ('learning_materials', 'Learning Materials')], default='learning_materials', max_length=50),
        ),
    ]
