# Generated by Django 5.1.6 on 2025-06-16 07:33

import backend.apps.pdf_service.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_service', '0004_document_upload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('syllabus', 'Syllabus'), ('exam', 'Exam'), ('note', 'Note'), ('unknown', 'Unknown')], default=backend.apps.pdf_service.constants.DocumentType['UNKNOWN'], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='pdf_service.document')),
            ],
        ),
    ]
