# Generated by Django 5.2.3 on 2025-07-07 19:21

import backend.apps.pdf_service.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_service', '0005_document_document_type_processeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('syllabus', 'Syllabus'), ('exam', 'Exam'), ('note', 'Note'), ('study_content', 'Study_Content'), ('unknown', 'Unknown')], default=backend.apps.pdf_service.constants.DocumentType['UNKNOWN'], max_length=20, null=True),
        ),
    ]
