# Generated by Django 5.1.6 on 2025-02-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_title'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardset',
            name='pdf_document',
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='title',
            field=models.CharField(default='Untitled Flashcard Set', max_length=255),
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
