# Generated by Django 5.1.6 on 2025-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_remove_flashcardset_pdf_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
