name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install schemathesis
    - name: Run Tests
      run: |
        python manage.py test
    - name: API Contract Testing (Legacy Mode)
      run: |
        ENABLE_STI=false schemathesis run --checks all openapi_v2.yaml
    - name: API Contract Testing (STI Mode)
      run: |
        ENABLE_STI=true schemathesis run --checks all openapi_v2.yaml
